import { Meal, TiffinPlan, ChefProfile, UserReview } from './types';

export const CHEFS: ChefProfile[] = [
  {
    id: 'chef-anita',
    name: 'Chef Anita Sharma',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=200&h=200',
    specialty: 'North Indian & Punjabi Comforts',
    location: 'Sector 12, Dwarka, Delhi',
    experience: '15+ Years cooking for family and community',
    bio: 'Anita learned traditional Punjabi recipes from her grandmother. She believes that slow-cooking and freshly ground spices are the secret to authentic "Maa ke hath ka khana". All her meals are prepared with hand-churned white butter and pure ghee.',
    hygieneRating: 4.9,
    rating: 4.8,
    reviewsCount: 342,
  },
  {
    id: 'chef-meenakshi',
    name: 'Chef Meenakshi Iyer',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=200&h=200',
    specialty: 'Traditional South Indian & Vedic Cuisine',
    location: '4th Block, Jayanagar, Bengaluru',
    experience: '10+ Years as a home-based catering expert',
    bio: 'Meenakshi specializes in healthy, wholesome South Indian meals cooked according to Vedic principles. She uses local organic ingredients and wood-pressed oils, ensuring every dish is easy to digest yet rich in authentic regional flavors.',
    hygieneRating: 5.0,
    rating: 4.9,
    reviewsCount: 289,
  },
  {
    id: 'chef-piyali',
    name: 'Chef Piyali Banik',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=200&h=200',
    specialty: 'Authentic Bengali & East Indian',
    location: 'Salt Lake City, Sector 2, Kolkata',
    experience: '12+ Years hosting home supper clubs',
    bio: 'Piyali brings the comforting culinary heritage of Bengal to your doorstep. From perfectly puffed Luchis with Alur Dom to delicate mustard fish curries and soft sandesh, she packs every delivery box with utmost warmth and hygiene.',
    hygieneRating: 4.8,
    rating: 4.7,
    reviewsCount: 156,
  },
  {
    id: 'chef-savita',
    name: 'Chef Savita Patil',
    avatar: 'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?auto=format&fit=crop&q=80&w=200&h=200',
    specialty: 'Maharashtrian & Western Spices',
    location: 'Kothrud, Pune',
    experience: '8+ Years running a local tiffin kitchen',
    bio: 'Savita is passionate about preserving traditional Maharashtrian home-style recipes. Her specialties include hand-rolled Puran Poli, spiced Pitla with Bhakri, and local peanut-tempered gravies. She uses spices prepared fresh in her own kitchen stone-mortar.',
    hygieneRating: 4.9,
    rating: 4.8,
    reviewsCount: 210,
  }
];

export const MEALS: Meal[] = [
  // North Indian
  {
    id: 'paneer-butter-masala',
    name: 'Paneer Butter Masala',
    description: 'Fresh cottage cheese cubes simmered in a silky tomato, cashew and cream gravy, finished with fresh butter and dried fenugreek leaves.',
    price: 189,
    image: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&q=80&w=600',
    category: 'north',
    isVeg: true,
    isJain: false,
    isKeto: false,
    isPopular: true,
    chefId: 'chef-anita',
    spicyLevel: 1,
    calories: 340,
  },
  {
    id: 'dal-makhani',
    name: 'Slow-Cooked Dal Makhani',
    description: 'Black lentils and red kidney beans slow-simmered overnight over low coal embers, enriched with cream and homemade white butter.',
    price: 159,
    image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&q=80&w=600',
    category: 'north',
    isVeg: true,
    isJain: false,
    isKeto: false,
    isPopular: true,
    chefId: 'chef-anita',
    spicyLevel: 1,
    calories: 290,
  },
  {
    id: 'home-aloo-gobi',
    name: 'Maa ki Aloo Gobi Adraki',
    description: 'Dry roasted fresh cauliflower and baby potatoes tossed with julienned ginger, green chillies, coriander, and freshly ground garam masala.',
    price: 129,
    image: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&q=80&w=600',
    category: 'north',
    isVeg: true,
    isJain: true,
    isKeto: false,
    chefId: 'chef-anita',
    spicyLevel: 2,
    calories: 180,
  },
  {
    id: 'tari-chicken-curry',
    name: 'Tari Wali Homestyle Chicken',
    description: 'Tender chicken pieces cooked in a light, fragrant onion-tomato broth with whole bay leaves, black cardamom, and ginger. Just like home.',
    price: 229,
    image: 'https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?auto=format&fit=crop&q=80&w=600',
    category: 'north',
    isVeg: false,
    isJain: false,
    isKeto: true,
    isPopular: true,
    chefId: 'chef-anita',
    spicyLevel: 2,
    calories: 420,
  },

  // South Indian
  {
    id: 'sambar-idli',
    name: 'Fluffy Idlis in Traditional Sambhar',
    description: 'Three super-soft, steamed fermented rice & black lentil cakes submerged in hot, tangy sambar made with freshly roasted spices and organic drumsticks.',
    price: 99,
    image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&q=80&w=600',
    category: 'south',
    isVeg: true,
    isJain: false,
    isKeto: false,
    chefId: 'chef-meenakshi',
    spicyLevel: 1,
    calories: 190,
  },
  {
    id: 'masala-dosa',
    name: 'Home-Style Butter Masala Dosa',
    description: 'Crisp, gold-brown crepe rolled with a simple spiced potato-onion filling, accompanied by fresh coconut chutney and tomato-lentil chutney.',
    price: 119,
    image: 'https://images.unsplash.com/photo-1668236543090-82eba5ee5976?auto=format&fit=crop&q=80&w=600',
    category: 'south',
    isVeg: true,
    isJain: false,
    isKeto: false,
    isPopular: true,
    chefId: 'chef-meenakshi',
    spicyLevel: 1,
    calories: 280,
  },
  {
    id: 'lemon-rice',
    name: 'Tangy Lemon Rice with Peanuts',
    description: 'Steamed basmati rice tossed with fresh lemon juice, turmeric, and tempered with mustard seeds, curry leaves, ginger, and crispy split chickpeas.',
    price: 109,
    image: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&q=80&w=600',
    category: 'south',
    isVeg: true,
    isJain: true,
    isKeto: false,
    chefId: 'chef-meenakshi',
    spicyLevel: 1,
    calories: 220,
  },

  // East Indian
  {
    id: 'luchi-alur-dom',
    name: 'Bengali Alur Dom & Fluffy Luchis',
    description: 'Slow-simmered, spice-crusted baby potatoes in a thick, rich tomato-cumin-ginger gravy, served with 4 fluffy, deep-fried refined flour Luchis.',
    price: 139,
    image: 'https://images.unsplash.com/photo-1589302168068-964664d93dc0?auto=format&fit=crop&q=80&w=600',
    category: 'east',
    isVeg: true,
    isJain: false,
    isKeto: false,
    isPopular: true,
    chefId: 'chef-piyali',
    spicyLevel: 2,
    calories: 310,
  },
  {
    id: 'shorshe-maach',
    name: 'Shorshe Maach (Mustard Fish Curry)',
    description: 'Fresh water Rohu fish steaks fried in pure mustard oil and cooked in a sharp, pungent gravy of fresh yellow mustard paste and green chillies.',
    price: 249,
    image: 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&q=80&w=600',
    category: 'east',
    isVeg: false,
    isJain: false,
    isKeto: true,
    chefId: 'chef-piyali',
    spicyLevel: 3,
    calories: 360,
  },

  // West Indian
  {
    id: 'puran-poli',
    name: 'Sajuk Ghee Puran Poli (2 Pcs)',
    description: 'Golden wheat flatbreads stuffed with sweet, aromatic mixture of cooked chana dal and jaggery flavored with nutmeg and cardamom. Smothered in pure ghee.',
    price: 119,
    image: 'https://images.unsplash.com/photo-1505253716362-afaea1d3d1af?auto=format&fit=crop&q=80&w=600',
    category: 'west',
    isVeg: true,
    isJain: true,
    isKeto: false,
    isPopular: true,
    chefId: 'chef-savita',
    spicyLevel: 1,
    calories: 380,
  },
  {
    id: 'sev-tamatar-sabzi',
    name: 'Kathiyawadi Sev Tamatar Sabzi',
    description: 'Tangy, spicy tomato curry cooked with garlic, dry spices, and jaggery, topped with crunchy thick gram flour Sev (noodles) just before serving.',
    price: 129,
    image: 'https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?auto=format&fit=crop&q=80&w=600',
    category: 'west',
    isVeg: true,
    isJain: false,
    isKeto: false,
    chefId: 'chef-savita',
    spicyLevel: 3,
    calories: 240,
  },

  // Healthy & Vedic
  {
    id: 'moong-dal-khichdi',
    name: 'Maa ki Parshad Moong Dal Khichdi',
    description: 'A comforting, easily digestible recipe of broken rice and yellow split lentils cooked with seasonal carrots, green peas, tempered with cow ghee and cumin seeds.',
    price: 119,
    image: 'https://images.unsplash.com/photo-1605333396915-47ed6b68a00e?auto=format&fit=crop&q=80&w=600',
    category: 'healthy',
    isVeg: true,
    isJain: true,
    isKeto: false,
    isPopular: true,
    chefId: 'chef-meenakshi',
    spicyLevel: 1,
    calories: 210,
  },
  {
    id: 'quinoa-biryani',
    name: 'Supergrain Quinoa Veg Biryani',
    description: 'Organic high-protein quinoa cooked in dum-style with carrots, beans, cauliflower, green peas, and fresh mint, using wood-pressed coconut oil.',
    price: 179,
    image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&q=80&w=600',
    category: 'healthy',
    isVeg: true,
    isJain: true,
    isKeto: true,
    chefId: 'chef-meenakshi',
    spicyLevel: 2,
    calories: 250,
  },

  // Desserts
  {
    id: 'gulab-jamun',
    name: 'Warm Rose Gulab Jamun (2 Pcs)',
    description: 'Soft, melt-in-the-mouth khoya and paneer dumplings fried to a perfect golden brown, then soaked in sweet rosewater and cardamom infused sugar syrup.',
    price: 69,
    image: 'https://images.unsplash.com/photo-1587314168485-3236d6710814?auto=format&fit=crop&q=80&w=600',
    category: 'desserts',
    isVeg: true,
    isJain: true,
    isKeto: false,
    isPopular: true,
    chefId: 'chef-anita',
    spicyLevel: 1,
    calories: 220,
  },
  {
    id: 'gajar-halwa',
    name: 'Slow-Stirred Desi Gajar Ka Halwa',
    description: 'Fresh red carrots grated and slow-cooked for hours with whole milk, homemade khoya, sugar, and golden ghee, garnished with toasted almonds and cashews.',
    price: 89,
    image: 'https://images.unsplash.com/photo-1563729784474-d77dbb933a9e?auto=format&fit=crop&q=80&w=600',
    category: 'desserts',
    isVeg: true,
    isJain: true,
    isKeto: false,
    chefId: 'chef-anita',
    spicyLevel: 1,
    calories: 270,
  }
];

export const TIFFIN_PLANS: TiffinPlan[] = [
  {
    id: 'daily-veg-tiffin',
    name: 'Ghar Ka Swaad (Veg)',
    description: 'Perfect for working professionals & students. Simple, everyday homestyle meals cooked with minimal oil and spices, just like what you eat at home.',
    pricePerWeek: 649,
    pricePerMonth: 2299,
    image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&q=80&w=600',
    includes: [
      '1 Comforting Dal (Dal Tadka, Panchmel, or Sambhar)',
      '1 Seasonal Dry Sabzi (Bhindi, Aloo Gobi, or Ivy Gourd)',
      '4 Hot, Hand-Rolled Whole Wheat Phulkas (Tawa Rotis)',
      'Steamed Basmati Rice / Jeera Rice',
      'Fresh Garden Cucumber Salad & Roasted Papad'
    ],
    diet: 'veg',
  },
  {
    id: 'daily-nonveg-tiffin',
    name: 'Home Chef Special (Non-Veg)',
    description: 'Enjoy a rich home-cooked feast with traditional chicken or fish curries. A balance of delicious chicken curries, light egg curries, and rich lentil sides.',
    pricePerWeek: 849,
    pricePerMonth: 2999,
    image: 'https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?auto=format&fit=crop&q=80&w=600',
    includes: [
      '1 Tari Wali Chicken Curry, Egg Roast, or Fish Curry',
      '1 Homestyle Yellow Dal / Spiced Chickpeas',
      '4 Hot Whole Wheat Phulkas or 2 Laccha Parathas',
      'Fragrant Cumin Rice or Peas Pulao',
      'Spiced Onion Lachha & Mint Chutney'
    ],
    diet: 'non-veg',
  },
  {
    id: 'healthy-cleanse-tiffin',
    name: 'Vedic Wellness & Keto Box',
    description: 'Nourish your mind and body with lightweight, gluten-free, organic, and protein-focused meals prepared in unrefined wood-pressed sesame or olive oils.',
    pricePerWeek: 899,
    pricePerMonth: 3299,
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&q=80&w=600',
    includes: [
      '1 Protein Bowl (Paneer Bhurji, Grilled Tofu, or Herb Chicken)',
      '1 Ayurvedic Yellow Moong Dal or Spinach Lentils',
      '3 Multigrain Jowar/Bajra Rotis or Quinoa Rice',
      'Sautéed Broccoli, Zucchini & Sprouts Salad',
      'Digestive Buttermilk (Chaas) with roasted cumin'
    ],
    diet: 'keto',
  },
  {
    id: 'jain-sattva-tiffin',
    name: 'Sattvik Devotion (Jain)',
    description: 'Strictly Satvik food prepared with no onion, no garlic, and no root vegetables. Extremely hygienic cooking standards in a separate dedicated kitchen space.',
    pricePerWeek: 699,
    pricePerMonth: 2499,
    image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&q=80&w=600',
    includes: [
      '1 Satvik Dal (Yellow Moong Dal or Tomato Lentil Dal)',
      '1 Pure Veg Sabzi (Cabbage Sambharo, Bhindi Kurkuri, or Kaddu)',
      '4 Soft Phulkas topped with Cow Ghee',
      'Pure Steamed Rice',
      'Refreshing Curd (Yogurt) with pomegranate seeds'
    ],
    diet: 'jain',
  }
];

export const USER_REVIEWS: UserReview[] = [
  {
    id: 'rev-1',
    userName: 'Aishwarya Deshmukh',
    rating: 5,
    comment: 'The Dal Makhani from Chef Anita tastes exactly like what my mom makes in Punjab. The rotis are soft even when they reach my office. Best lunch decision ever!',
    date: 'July 15, 2026',
    mealName: 'Slow-Cooked Dal Makhani',
  },
  {
    id: 'rev-2',
    userName: 'Karthik Subramanian',
    rating: 5,
    comment: 'Subscribed to the Sattvik/Jain tiffin box for my parents and they are extremely happy with the purity, cleanliness, and timely delivery. Meenakshi iyer is amazing.',
    date: 'July 12, 2026',
    mealName: 'Sattvik Devotion (Jain)',
  },
  {
    id: 'rev-3',
    userName: 'Soham Mukherjee',
    rating: 4,
    comment: 'Shorshe Maach from Piyali is out of this world! Perfect pungency of mustard oil and fresh fish. Slightly hot, but perfect with hot steamed rice.',
    date: 'July 10, 2026',
    mealName: 'Shorshe Maach (Mustard Fish Curry)',
  },
  {
    id: 'rev-4',
    userName: 'Neha Patil',
    rating: 5,
    comment: 'Puran Poli was filled so generously with sweet dal and it had that beautiful aroma of nutmeg and ghee. Will order every week!',
    date: 'July 18, 2026',
    mealName: 'Sajuk Ghee Puran Poli (2 Pcs)',
  }
];

// Components for Custom Thali Builder
export const THALI_OPTIONS = {
  dals: [
    { id: 'dal-tadka', name: 'Home Dal Tadka (Yellow Lentils)', price: 40, isVeg: true, image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&q=80&w=200' },
    { id: 'dal-makhani-mini', name: 'Creamy Dal Makhani', price: 55, isVeg: true, image: 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&q=80&w=200' },
    { id: 'sambhar-mini', name: 'Tangy Sambar', price: 40, isVeg: true, image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&q=80&w=200' },
  ],
  curries: [
    { id: 'paneer-lababdar', name: 'Paneer Lababdar', price: 75, isVeg: true, image: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&q=80&w=200' },
    { id: 'aloo-jeera', name: 'Homestyle Aloo Jeera', price: 45, isVeg: true, image: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&q=80&w=200' },
    { id: 'chana-masala', name: 'Rawal Pindi Chana Masala', price: 55, isVeg: true, image: 'https://images.unsplash.com/photo-1596797038530-2c107229654b?auto=format&fit=crop&q=80&w=200' },
    { id: 'home-chicken-curry-mini', name: 'Tari Wali Chicken Curry', price: 95, isVeg: false, image: 'https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?auto=format&fit=crop&q=80&w=200' },
    { id: 'mix-veg', name: 'Mix Seasonal Dry Veg', price: 50, isVeg: true, image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&q=80&w=200' },
  ],
  rices: [
    { id: 'steam-rice', name: 'Steamed Basmati Rice', price: 30, isVeg: true, image: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&q=80&w=200' },
    { id: 'jeera-rice', name: 'Jeera Rice (Cumin Scented)', price: 40, isVeg: true, image: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&q=80&w=200' },
    { id: 'peas-pulao', name: 'Garden Peas Pulao', price: 45, isVeg: true, image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&q=80&w=200' },
  ],
  breads: [
    { id: 'roti-plain', name: 'Plain Chapati / Phulka (2 Pcs)', price: 20, isVeg: true, image: 'https://images.unsplash.com/photo-1505253716362-afaea1d3d1af?auto=format&fit=crop&q=80&w=200' },
    { id: 'roti-butter', name: 'Butter Tawa Roti (2 Pcs)', price: 25, isVeg: true, image: 'https://images.unsplash.com/photo-1505253716362-afaea1d3d1af?auto=format&fit=crop&q=80&w=200' },
    { id: 'laccha-paratha', name: 'Crisp Laccha Paratha (1 Pc)', price: 30, isVeg: true, image: 'https://images.unsplash.com/photo-1505253716362-afaea1d3d1af?auto=format&fit=crop&q=80&w=200' },
  ],
  sweets: [
    { id: 'gulab-jamun-1', name: 'Warm Gulab Jamun (1 Pc)', price: 30, isVeg: true, image: 'https://images.unsplash.com/photo-1587314168485-3236d6710814?auto=format&fit=crop&q=80&w=200' },
    { id: 'kheer-cup', name: 'Elachi Rice Kheer Cup', price: 40, isVeg: true, image: 'https://images.unsplash.com/photo-1587314168485-3236d6710814?auto=format&fit=crop&q=80&w=200' },
    { id: 'boondi-raita', name: 'Spiced Boondi Raita', price: 25, isVeg: true, image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&q=80&w=200' },
    { id: 'mango-pickle', name: 'Ghar ka Aam ka Achar', price: 10, isVeg: true, image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&q=80&w=200' },
  ]
};
